---
title: "calculating_comm_div_metrics_fish"
author: "CEB"
date: '2023-04-28'
output: html_document
---


#load packages
```{r}
library(tidyverse) #for everything
library(vegan) # for diversity and community analyses

```


#load raw data
```{r}

#raw fish data----
tet_fish_raw<-read.csv("../raw_data/Tetiaroa_fish_uvc_focal_Nov21_clean_w_biomass.csv", stringsAsFactors = TRUE)
str(tet_fish_raw)

levels(tet_fish_raw$Site)

##REMOVE REIONO SITE 2 TRANSECT NA - this was originally called transect 1, but it was too shallow for film and ended up offcourse, so did an extra transect here. In fish data called 1-5, but in benthic data transect 1 (og) had already been removed. So changed name in all. Now should match.

tet_fish_raw<-
  tet_fish_raw%>%
  filter(Transect!="na")%>%
  droplevels()
tet_fish_raw

##also load site metadata:----
tet_site_meta<-read.csv("../../metadata/TARP_Nov2021_site_metadata_version2.csv", stringsAsFactors = TRUE)
str(tet_site_meta)

#also load transect metadata:-----


#create new columns to match metadata, and remove capitalization of motu----
tet_fish_raw<-
  tet_fish_raw%>%
  rename_with(tolower)%>%
  mutate(motu = str_to_lower(motu))%>%
  mutate(island.side = case_when(grepl("west", site, ignore.case = TRUE)~"west",
                                 grepl("east", site, ignore.case = TRUE)~"east",
                                 grepl("south", site, ignore.case = TRUE)~"south",
                                 grepl("north", site, ignore.case = TRUE)~"north"))

#combine with site metadata----
tet_fish_raw_meta<-left_join(tet_fish_raw, tet_site_meta, by = c("motu", "island.side"))%>%
  relocate(island.side:rat.eradication.status, .after = motu)
tet_fish_raw_meta

#check if worked by seeing if any NA's:
tet_fish_raw_meta%>%
filter(is.na(site.name))
#all good

```

#sum by transect, change to wide to calculate diversity metrics:
```{r}
str(tet_fish_raw_meta)

#first sum by transect----
tet_fish_raw_meta_trans<-
tet_fish_raw_meta%>%
  group_by(motu, site.name, wind.exposure, rat.eradication.status, transect, species)%>%
  summarize(density_ha_trans = sum(density_ha),
            biomass_kgha_trans = sum(biomass_kg_ha))%>%
  mutate(species = str_replace(species, " ", "."),
         species = as.factor(species))
  #add . in species names so don't mess up column names when pivot wider
tet_fish_raw_meta_trans

#make sure no dumb species typos:
levels(tet_fish_raw_meta_trans$species) #all good

#make wide - one for density, one for biomass
tet_fish_raw_trans_wide_density<-
  tet_fish_raw_meta_trans%>%
  pivot_wider(id_cols = c(motu, site.name, wind.exposure, rat.eradication.status, transect), 
              values_from = density_ha_trans, names_from = species, values_fill = 0)
tet_fish_raw_trans_wide_density


tet_fish_raw_trans_wide_biomass<-
  tet_fish_raw_meta_trans%>%
  pivot_wider(id_cols = c(motu, site.name, wind.exposure, rat.eradication.status, transect), 
              values_from = biomass_kgha_trans, names_from = species, values_fill = 0)
tet_fish_raw_trans_wide_biomass

```


#calculate diversity:
```{r}
str(tet_fish_raw_trans_wide_density)

#make species only table and env only table: ----
tet_fish_raw_trans_wide_density_sp<-
  tet_fish_raw_trans_wide_density%>%
  ungroup()%>%
  select(Acanthurus.nigricauda:Labroides.bicolor)
tet_fish_raw_trans_wide_density_sp


tet_fish_raw_trans_wide_density_env<-
  tet_fish_raw_trans_wide_density%>%
  ungroup()%>%
  select(motu:transect)
tet_fish_raw_trans_wide_density_env

###calculate diversity----
observed<-specnumber(tet_fish_raw_trans_wide_density_sp)
shannon<-diversity(tet_fish_raw_trans_wide_density_sp, "shannon")
evenness<-diversity(tet_fish_raw_trans_wide_density_sp)/log(specnumber(tet_fish_raw_trans_wide_density_sp)) #J = H/log(specnumber(BCI))
sum_dens<-rowSums(tet_fish_raw_trans_wide_density_sp)

tet_fish_dens_diversity<-
tet_fish_raw_trans_wide_density_env %>%
  cbind(observed, shannon, evenness, sum_dens)

tet_fish_dens_diversity


#quick plots----
tet_fish_dens_diversity%>%
  ggplot(aes(x = motu, y = observed, color = wind.exposure, fill = wind.exposure))+
  geom_boxplot(outlier.size=0, outlier.stroke=0,outlier.shape=NA, alpha = 0.1) +
  geom_point(size = 3, pch=21, alpha= .6, position=position_jitterdodge())+
  theme_bw()

tet_fish_dens_diversity%>%
  ggplot(aes(x = motu, y = shannon, color = wind.exposure, fill = wind.exposure))+
  geom_boxplot(outlier.size=0, outlier.stroke=0,outlier.shape=NA, alpha = 0.1) +
  geom_point(size = 3, pch=21, alpha= .6, position=position_jitterdodge())+
  theme_bw()


tet_fish_dens_diversity%>%
  ggplot(aes(x = motu, y = evenness, color = wind.exposure, fill = wind.exposure))+
  geom_boxplot(outlier.size=0, outlier.stroke=0,outlier.shape=NA, alpha = 0.1) +
  geom_point(size = 3, pch=21, alpha= .6, position=position_jitterdodge())+
  theme_bw()


tet_fish_dens_diversity%>%
  ggplot(aes(x = motu, y = sum_dens, color = wind.exposure, fill = wind.exposure))+
  geom_boxplot(outlier.size=0, outlier.stroke=0,outlier.shape=NA, alpha = 0.1) +
  geom_point(size = 3, pch=21, alpha= .6, position=position_jitterdodge())+
  theme_bw()


tet_fish_dens_diversity%>%
  ggplot(aes(x = motu, y = log(sum_dens), color = wind.exposure, fill = wind.exposure))+
  geom_boxplot(outlier.size=0, outlier.stroke=0,outlier.shape=NA, alpha = 0.1) +
  geom_point(size = 3, pch=21, alpha= .6, position=position_jitterdodge())+
  theme_bw()


##maybe interesting - diveristy metrics definitely not following same pattern as density (and biomass)

```


#run NMDS on fish density
```{r}
##NEED TO LOG DENSITY PROBABLY******

###RUN NMDS----
nmds_fish_focal<-metaMDS(tet_fish_raw_trans_wide_density_sp, distance = "bray", trymax=200, k=2)
nmds_fish_focal
#stress = 0.2390068 - not great. update k??
plot(nmds_fish_focal)
scores(nmds_fish_focal, display="species")


#look at plot and centroids, for now just motu and exposure (so sitename). will need to add explanatory variables
plot(nmds_fish_focal)
ord.fit<-envfit(nmds_fish_focal~site.name, data = tet_fish_raw_trans_wide_density, na.rm=TRUE)
ord.fit #looks like some differences among motu
plot(ord.fit)
#draw polygons
ordihull(nmds_fish_focal, tet_fish_raw_trans_wide_density$site.name, pty=3)
#looks like some differences among sites, now run statistics


#PERMANOVA
#anosim more influenced by dispersion, so use adonis
#run analysis
ad_fish1<-adonis2(tet_fish_raw_trans_wide_density_sp ~ site.name, data = tet_fish_raw_trans_wide_density, method="euclidean")
ad_fish1
#significant


#test dispersion using PERMDISP
mod_fish <- betadisper(vegdist(tet_fish_raw_trans_wide_density_sp, method = "euclidean"), tet_fish_raw_trans_wide_density$site.name)
mod_fish
#test for overall differences
anova(mod_fish)
#marginally different.....

##extract site scores-----


##run with log density----
tet_fish_raw_trans_wide_density_sp_log<-
  log(tet_fish_raw_trans_wide_density_sp+1)


nmds_fish_focal_log<-metaMDS(tet_fish_raw_trans_wide_density_sp_log, distance = "bray", trymax=200, k=3)
nmds_fish_focal_log
#stress = 0.08077999 with 5, 0.1086954 with 4, 0.1560843 with 3, 0.2387702 with 2.....May want to use 3 dimensions because that stress is WAY better than 2 dimensions.

#try without autotransform***:
nmds_fish_focal_log<-metaMDS(tet_fish_raw_trans_wide_density_sp_log, distance = "bray", trymax=200, k=3, autotransform = FALSE)
nmds_fish_focal_log
#2 axes stress = 0.2368073, 3 axes = 0.1576411
plot(nmds_fish_focal_log)
scores(nmds_fish_focal_log, display="species")

#Is this good?  Clarke (1993, p. 126) suggests the following rules of thumb for stress values:
#Stress (0-1 scale)	Interpretation
#< 0.05	Excellent representation with no prospect of misinterpretation
#< 0.10	Good ordination with no real risk of drawing false inferences
#< 0.20	Can be useful but has potential to mislead.  In particular, shouldn’t place too much reliance on the details
#> 0.20	Could be dangerous to interpret
#> 0.35	Samples placed essentially at random; little relation to original ranked distances


##check distance measure:
rankindex(tet_fish_raw_trans_wide_density_env$site.name, tet_fish_raw_trans_wide_density_sp_log)
#higher is better - euclidean may be best...
nmds_fish_focal_log_euc<-metaMDS(tet_fish_raw_trans_wide_density_sp_log, distance = "euclidean", trymax=200, k=2, autotransform = FALSE)
nmds_fish_focal_log_euc #0.2353211 - not any better


##proceed with 3-axis NMDS:----
plot(nmds_fish_focal_log)
scores(nmds_fish_focal_log, display="species")


#look at plot and centroids, for now just motu and exposure (so sitename). will need to add explanatory variables
plot(nmds_fish_focal_log)
ord.fit<-envfit(nmds_fish_focal_log~site.name, data = tet_fish_raw_trans_wide_density, na.rm=TRUE)
ord.fit #looks like some differences among motu
plot(ord.fit)
#draw polygons
ordihull(nmds_fish_focal, tet_fish_raw_trans_wide_density$site.name, pty=3)
#looks like some differences among sites, now run statistics


#PERMANOVA
#anosim more influenced by dispersion, so use adonis
#run analysis
ad_fish1_log<-adonis2(tet_fish_raw_trans_wide_density_sp_log ~ site.name, data = tet_fish_raw_trans_wide_density, method="euclidean")
ad_fish1_log
#site explains ~32% of variance


ad_fish2_log<-adonis2(tet_fish_raw_trans_wide_density_sp_log ~ motu*wind.exposure, data = tet_fish_raw_trans_wide_density, method="euclidean")
ad_fish2_log
#motu and motu*exposure sig. Explains 15 and 12% of variation, respectively


#test dispersion using PERMDISP
mod_fish_log <- betadisper(vegdist(tet_fish_raw_trans_wide_density_sp_log, method = "bray"), tet_fish_raw_trans_wide_density$site.name)
mod_fish_log
#test for overall differences
anova(mod_fish_log)
#not different

#extract distance to centroid - use TukeyHSD.betadisper from ?betadisper
dist_cent_fish_log <-betadisper(d = vegdist(tet_fish_raw_trans_wide_density_sp_log, method = "bray"),
                           group = tet_fish_raw_trans_wide_density$site.name,
                           type = "centroid", sqrt.dist = FALSE)
dist_cent_fish_log
TukeyHSD(dist_cent_fish_log,conf.level = .95) #okay this shows CI's for contrasts. note that conf.level affects intervals, but not p-values. 

dist_cent_fish_logdf<-
  cbind(tet_fish_raw_trans_wide_density_env, dist_cent_fish_log$distances) %>%
  rename(Distance_to_centroid = "dist_cent_fish_log$distances")
dist_cent_fish_logdf



##SIMPER analysis to test effects of species----
#by site:
sim_log_fish<-simper(tet_fish_raw_trans_wide_density_sp_log, tet_fish_raw_trans_wide_density$site.name, permutations = 999)
summary(sim_log_fish)

#by motu:
sim_log_fish_motu<-simper(tet_fish_raw_trans_wide_density_sp_log, tet_fish_raw_trans_wide_density$motu, permutations = 999)
summary(sim_log_fish_motu)

#by exposure:
sim_log_fish_exp<-simper(tet_fish_raw_trans_wide_density_sp_log, tet_fish_raw_trans_wide_density$wind.exposure, permutations = 999)
summary(sim_log_fish_exp)



##extract site/transect scores----
fish_log_spp.sc <- as.data.frame(scores(nmds_fish_focal_log, "species"))  #Using the scores function from vegan to extract the species scores and convert to a data.frame
fish_log_spp.sc<-
  fish_log_spp.sc%>%
  rownames_to_column(var="Species") # create a column of species, from the rownames of species.scores


fish_log_site.sc <- scores(nmds_fish_focal_log, display = "sites", shrink = FALSE) 
fish_log_site.sc

#merge site.sc with metadata and dispersion
nmds_fish_log_site_scores<-
  bind_cols(dist_cent_fish_logdf,
                    as_tibble(fish_log_site.sc))
nmds_fish_log_site_scores


#plot just to see----

#get hull data:
site.A1 <- nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == "A1", ][chull(nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == 
    "A1", c("NMDS1", "NMDS2")]), ]

site.A2 <- nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == "A2", ][chull(nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == 
    "A2", c("NMDS1", "NMDS2")]), ]  

site.Re1 <- nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == "Re1", ][chull(nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == 
    "Re1", c("NMDS1", "NMDS2")]), ]

site.Re2<- nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == "Re2", ][chull(nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == 
    "Re2", c("NMDS1", "NMDS2")]), ]  

site.Rm1 <- nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == "Rm1", ][chull(nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == 
    "Rm1", c("NMDS1", "NMDS2")]), ]

site.Rm2<- nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == "Rm2", ][chull(nmds_fish_log_site_scores[nmds_fish_log_site_scores$site.name == 
    "Rm2", c("NMDS1", "NMDS2")]), ]  

hull.data <- rbind(site.A1, site.A2, site.Re1, site.Re2, site.Rm1, site.Rm2)  #combine
hull.data

ggplot() + 
  geom_text(data=fish_log_spp.sc,aes(x=NMDS1,y=NMDS2,label=Species), alpha = .2) +  # add the species labels - 
  geom_point(data=nmds_fish_log_site_scores,aes(x=NMDS1,y=NMDS2,colour=site.name, fill = site.name, pch = site.name), stat="identity", size=5, alpha = .9) +
  geom_polygon(data=hull.data,aes(x=NMDS1,y=NMDS2,fill=site.name,group=site.name),alpha=0.30) + # add the convex hulls
  theme_bw() + 
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), #remove gray boxes
        text = element_text(size=20))
        #legend.title = element_blank()) #remove legend title
        #legend.box.background = element_rect(colour = "black", fill='white', linetype='solid', size=1), 
       # legend.justification=c(1,.9), legend.position=c(1,.9))  #  fix legend


#plot NMDS 2-3 (don't bother with hull data for now)-----
ggplot() + 
  geom_text(data=fish_log_spp.sc,aes(x=NMDS2,y=NMDS3,label=Species), alpha = .2) +  # add the species labels - 
  geom_point(data=nmds_fish_log_site_scores,aes(x=NMDS2,y=NMDS3,colour=site.name, fill = site.name, pch = site.name), stat="identity", size=5, alpha = .9) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), #remove gray boxes
        text = element_text(size=20))
        #legend.title = element_blank()) #remove legend title
        #legend.box.background = element_rect(colour = "black", fill='white', linetype='solid', size=1), 
       # legend.justification=c(1,.9), legend.position=c(1,.9))  #  fix legend

```

##look at relative abundance of most common species and/or trophic groups: 
```{r}
#top 10 species by density: ----
tet_fish_raw_trans_wide_density%>%
  ungroup()%>%
  summarize(across(where(is.numeric), ~sum(.x)))%>%
  pivot_longer(everything(), names_to = "species", values_to = "sum_density")%>%
  arrange(desc(sum_density))

#Stegastes.nigricans	52633.33334			
#Pomacentrus.pavo	11000.00000			
#Chrysiptera.brownriggii	10500.00000			
#Acanthurus.triostegus	7866.66667			
#Stegastes.albifasciatus	7666.66667			
#Thalassoma.hardwicke	6733.33333			
#Dascyllus.aruanus	6166.66667			
#Chlorurus.spilurus	5866.66667			
#Scarus.psittacus	5666.66667			
#Ctenochaetus.striatus	4800.00000			


#top 10 species by biomass: ----
tet_fish_raw_trans_wide_biomass%>%
  ungroup()%>%
  summarize(across(where(is.numeric), ~sum(.x)))%>%
  pivot_longer(everything(), names_to = "species", values_to = "sum_biomass")%>%
  arrange(desc(sum_biomass))

#Scarus.psittacus	1.215512e+03			
#Ctenochaetus.striatus	1.175302e+03			
#Acanthurus.nigricauda	1.057008e+03			
#Chlorurus.spilurus	1.018997e+03			
#Stegastes.nigricans	9.085508e+02			
#Crenimugil.crenilabis	7.347832e+02			
#Lutjanus.fulvus	7.221506e+02			
#Hipposcarus.longiceps	6.736756e+02			
#Acanthurus.triostegus	4.182148e+02			
#Caranx.melampygus	4.005061e+02	



```

###look at trophic levels by transect----
```{r}
#for this use biomass, because that's what trophic pyramids based on:
tet_fish_raw_meta%>%
  group_by(motu, site.name, wind.exposure, rat.eradication.status, transect, species)%>%
  summarize(density_ha_trans = sum(density_ha),
            biomass_kgha_trans = sum(biomass_kg_ha))%>%
  mutate(species = str_replace(species, " ", "."),
         species = as.factor(species))


tet_fish_raw_trans_wide_biomass<-
  tet_fish_raw_meta%>%
  pivot_wider(id_cols = c(motu, site.name, wind.exposure, rat.eradication.status, transect), 
              values_from = biomass_kgha_trans, names_from = species, values_fill = 0)
tet_fish_raw_trans_wide_biomass

tet_fish_dat_bio_trans_TL<-
tet_fish_raw_meta%>%
  mutate(trophic_bin = case_when(trophic_level<=2.5 ~ 1,
                                 trophic_level>2.5&trophic_level<=3 ~ 2,
                                 trophic_level>3&trophic_level<=3.5 ~ 3,
                                 trophic_level>3.5&trophic_level<=4 ~ 4,
                                 trophic_level>4 ~ 5))%>%
    group_by(motu, site.name, wind.exposure, rat.eradication.status, transect, trophic_bin)%>%
    summarize(sum_bio_tl_transect= sum(biomass_kg_ha))
tet_fish_dat_bio_trans_TL
#make wide to fill in missing 0s:

tet_fish_dat_bio_trans_TL_wide<-
  tet_fish_dat_bio_trans_TL%>%
  pivot_wider(id_cols = c(motu, site.name, wind.exposure, rat.eradication.status, transect), 
              values_from = sum_bio_tl_transect, names_from = trophic_bin, values_fill = 0, names_prefix = "TL_")
tet_fish_dat_bio_trans_TL_wide

##get relative abundance of each trophic level: 
tet_fish_dat_bio_trans_TL_rel_abund<-
  tet_fish_dat_bio_trans_TL_wide%>%
  rowwise()%>%
  mutate(sum_biomass_transect = sum(across(where(is.numeric))))%>%
  mutate(rel_bio_TL1 = TL_1/sum_biomass_transect,
         rel_bio_TL2 = TL_2/sum_biomass_transect,
         rel_bio_TL3 = TL_3/sum_biomass_transect,
         rel_bio_TL4 = TL_4/sum_biomass_transect,
         rel_bio_TL5 = TL_5/sum_biomass_transect)%>%
  ungroup()

tet_fish_dat_bio_trans_TL_rel_abund

###quick plot just to see----
tet_fish_dat_bio_trans_TL_rel_abund%>%
  select(c(motu:transect), c(rel_bio_TL1:rel_bio_TL5))%>%
  pivot_longer(c(rel_bio_TL1:rel_bio_TL5), names_to = "trophic_level", values_to = "rel_biomass_tl")%>%
  ggplot(aes(x = site.name, y = rel_biomass_tl, color = trophic_level, fill = trophic_level))+
  geom_boxplot()


tet_fish_dat_bio_trans_TL_rel_abund%>%
  select(c(motu:transect), c(rel_bio_TL1:rel_bio_TL5))%>%
  pivot_longer(c(rel_bio_TL1:rel_bio_TL5), names_to = "trophic_level", values_to = "rel_biomass_tl")%>%
  ggplot(aes(x = site.name, y = rel_biomass_tl, color = rat.eradication.status, fill = rat.eradication.status, alpha = .5))+
  geom_boxplot()+
  facet_wrap(~trophic_level, scales = "free")


#may be something interesting here.....look at absolute:
tet_fish_dat_bio_trans_TL_wide%>%
  pivot_longer(c(TL_1:TL_5), names_to = "trophic_level", values_to = "biomass_tl")%>%
  ggplot(aes(x = site.name, y = biomass_tl, color = rat.eradication.status, fill = rat.eradication.status, alpha = .5))+
  geom_boxplot()+
  facet_wrap(~trophic_level, scales = "free")

```



##combine transect data and save----
```{r}
str(nmds_fish_log_site_scores) #DENSITY
str(tet_fish_dens_diversity) #DENSITY
str(tet_fish_dat_bio_trans_TL_rel_abund) #BIOMASS relative trophic levels


tet_fish_dens_div_comm_dat<-
  left_join(tet_fish_dens_diversity, nmds_fish_log_site_scores,
            by = c("motu", "site.name", "wind.exposure", "rat.eradication.status", "transect"))
tet_fish_dens_div_comm_dat


tet_fish_div_comm_tl_dat<-
  left_join(tet_fish_dens_div_comm_dat, 
            select(tet_fish_dat_bio_trans_TL_rel_abund, c(site.name, transect, rel_bio_TL1, rel_bio_TL2, rel_bio_TL3, rel_bio_TL4, rel_bio_TL5)),
            by = c("site.name","transect"))
tet_fish_div_comm_tl_dat

#write.csv(tet_fish_dens_div_comm_dat, "../output/data/tet_fish_dens_div_comm_dat.csv")
#write.csv(tet_fish_div_comm_tl_dat, "../output/data/tet_fish_div_comm_tl_dat.csv")

```




