---
title: "seabirds_vs_fish_condition"
author: "CEB"
date: '2024-01-23'
output: html_document
---


#load packages
```{r}
library(tidyverse)

library(lme4)
library(car)
library(jtools)

library(emmeans)

library(corrplot)

```


#load data
```{r}
seabirds <- read.csv("../output/n15_seabirds_combined_no_iti.csv", strip.white = T, header = T)
fish_n15_cond <- read.csv("../../fish_isotopes/output/fish_n15_condition.csv", stringsAsFactors = TRUE)
algae_n15<-read.csv("../output/n15_seabirds_combined_no_iti.csv")

```



#merge data
```{r}
#make combined site name column in fish_n15

fishn15.seabirds.cond<-right_join(dplyr::select(seabirds, c("site.name", "breeding_biomass_kgha_side")), 
                                  dplyr::select(fish_n15_cond, c("site.name", "motu", "fish.id", "species", 
                                                   "month.caught", "year.caught", "protection", "TL.cm", "FL.cm", "SL.cm", "whole.weight.g", 
                                                    "n15", "c13", "n.percent", "c.percent")),
                            
                                   by = "site.name")%>%
  mutate(site.name = as.factor(site.name))
fishn15.seabirds.cond


##remove C. argus because n = 1 for Aie----
fishn15.seabirds.cond.r<-
  fishn15.seabirds.cond%>%
  filter(species != "Cephalopholis argus")%>%
  droplevels()


##check sample sizes, lengths per site:----
fishn15.seabirds.cond.r%>%
  group_by(species, site.name)%>%
  summarize(n = length(n15))

```

#run lm's USING ALGAE N15 AT 40
```{r}

#can use algae n15 at 40 m from shore as offshore, because this is present at all sites where we have fish
#because only one site per motu, random effects don't make sense, so run regular lm


#combine data with algae n15----
fishn15.seabirds.cond.algae<-
  left_join(fishn15.seabirds.cond.r, 
            select(algae_n15, c("site.name", "N.15_at_10m", "N.15_at_20m","N.15_at_30m","N.15_at_40m")), 
            by = "site.name")
fishn15.seabirds.cond.algae


#n15----
fish_n15_algae_lm<-lm(n15~ N.15_at_40m*species, 
                          data = fishn15.seabirds.cond.algae)
summary(fish_n15_algae_lm)
anova(fish_n15_algae_lm)#everything significant
Anova(fish_n15_algae_lm)
plot(fish_n15_algae_lm) #okay


#look at emmeans:
emtrends(fish_n15_algae_lm,  ~ species, var = "N.15_at_40m")
#looks like Ab sept and Ac tri both are positive. Other two trending towards positive but overlaps 0

test(emtrends(fish_n15_algae_lm, ~ species, var = "N.15_at_40m", adjust = "fdr"))
test(emtrends(fish_n15_algae_lm, ~ species, var = "N.15_at_40m", adjust = "none"))


# plot ---------
range(fishn15.seabirds.cond.algae$N.15_at_40m) #3.043333 6.003333
levels(fishn15.seabirds.cond.algae$species)
(mylist <- list(
    N.15_at_40m = seq(3, 6, by = 1),
    species = c("Abudefduf septemfasciatus", "Acanthurus triostegus" ,   "Lutjanus fulvus"     ,     
 "Stegastes nigricans")
))

emmip(fish_n15_algae_lm, species ~ N.15_at_40m, at = mylist, CIs = TRUE)



#plot raw data + lines: 
plot_dat<-emmip(fish_n15_algae_lm, species ~ N.15_at_40m, at = mylist, CIs = TRUE, plotit=FALSE)
plot_dat

fishn15.seabirds.cond.algae %>%
  group_by(species, N.15_at_40m)%>%
  summarize(mean_n15 = mean(n15))%>%
   ggplot(aes(x = N.15_at_40m, y = mean_n15, color = species, fill = species, group = species))+
  geom_point(alpha = .5)+
geom_line(data = plot_dat, aes(x = N.15_at_40m, y = yvar, color = species, group = species))+
  theme_bw() 


fishn15.seabirds.cond.algae %>%
      mutate(species = fct_relevel(species, c("Acanthurus triostegus", "Stegastes nigricans", "Abudefduf septemfasciatus", "Lutjanus fulvus")))%>%
  group_by(species, N.15_at_40m)%>%
  summarize(mean_n15 = mean(n15),
            se = sd(n15)/sqrt(length(n15)))%>%
   ggplot(aes(x = N.15_at_40m, y = mean_n15, color = species, fill = species, group = species))+
  geom_point(alpha = .8)+
  geom_errorbar(aes(ymin = mean_n15 - se, ymax = mean_n15+se))+
   geom_line(data = plot_dat, aes(x = N.15_at_40m, y = yvar, color = species, group = species))+
  ylab(expression(Fish~delta^15~N))+
  xlab(expression(Algae~delta^15~N))+
  labs(color = "", fill = "")+
  theme_bw() +
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
        legend.position = c(.2,.85),
        legend.background = element_blank())
        #legent.key = element_rect) #,
        #legend.direction = "horizontal",
      #  legend.box.background = element_rect(colour = "black"))


(mylist2 <- list(
    N.15_at_40m = c(3.043333, 5.233333, 6.003333),
    species = c("Abudefduf septemfasciatus", "Acanthurus triostegus" ,   "Lutjanus fulvus"     ,     
 "Stegastes nigricans")
))
plot_dat2<-emmip(fish_n15_algae_lm, species ~ N.15_at_40m, at = mylist2, CIs = TRUE, plotit=FALSE)
plot_dat2

fishn15.seabirds.cond.algae %>%
      mutate(species = fct_relevel(species, c("Acanthurus triostegus", "Stegastes nigricans", "Abudefduf septemfasciatus", "Lutjanus fulvus")))%>%
   ggplot(aes(x = N.15_at_40m, y = n15, color = species, fill = species, group = species))+
  geom_point(alpha = .5)+
   geom_ribbon(data = plot_dat2, aes(x = N.15_at_40m, y = yvar, ymin = LCL, ymax=UCL, fill = species), alpha = .2, lwd=0)+
 geom_line(data = plot_dat2, aes(x = N.15_at_40m, y = yvar, color = species, group = species))+
  theme_bw() 

fishn15.algan15.plot<-
fishn15.seabirds.cond.algae %>%
      mutate(species = fct_relevel(species, c("Acanthurus triostegus", "Stegastes nigricans", "Abudefduf septemfasciatus", "Lutjanus fulvus")))%>%
   ggplot(aes(x = N.15_at_40m, y = n15, color = species, fill = species, group = species))+
 # geom_point(alpha = .8)+
    geom_jitter(alpha = .7, width = .05, height = 0, size = 2.5)+
   geom_ribbon(data = plot_dat2, aes(x = N.15_at_40m, y = yvar, ymin = LCL, ymax=UCL, fill = species), alpha = .1, lwd=0)+
 geom_line(data = plot_dat2, aes(x = N.15_at_40m, y = yvar, color = species, group = species), lwd =1.5)+
  ylab(expression(Fish~delta^15~N))+
  xlab(expression(Algal~delta^15~N))+
  scale_fill_viridis_d(labels = c("Acanthurus triostegus (herbivore)", "Stegastes nigricans (herbivore)", "Abudefduf septemfasciatus (omnivore)", "Lutjanus fulvus (piscivore)"))+
  scale_color_viridis_d(labels = c("Acanthurus triostegus (herbivore)", "Stegastes nigricans (herbivore)", "Abudefduf septemfasciatus (omnivore)", "Lutjanus fulvus (piscivore)"))+
  labs(color = "", fill = "")+
  theme_bw() +
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
        legend.position = c(.2,.85),
        legend.background = element_blank())
        #legent.key = element_rect) #,
        #legend.direction = "horizontal",
      #  legend.box.background = element_rect(colour = "black"))
fishn15.algan15.plot


#ggsave("../output/seabird-fishn15/fish_n15_algae_n15_estplot_lines_points_update.jpg", plot = fishn15.algan15.plot, width = 7, height = 5)

#just raw data:
fishn15.seabirds.cond.algae %>%
   ggplot(aes(x = N.15_at_40m, y = n15, color = species, fill = species, group = species))+
  geom_point(alpha = .5)+
  stat_smooth(method = "lm")+
  theme_bw() 



```


##could be non-linear, so try comparing linear to quadratic
```{r}
#two ways to formulate polynomial, works with random effects, too:

fish_n15_algae_lm_quad1<-lm(n15~ N.15_at_40m*species + I(N.15_at_40m^2)*species, 
                          data = fishn15.seabirds.cond.algae)

fish_n15_algae_lm_quad2<-lm(n15~ N.15_at_40m*species + poly(N.15_at_40m,2)*species, 
                          data = fishn15.seabirds.cond.algae)
#some discussion online of poly() function giving different coefficient estimates, because it fits orthogonal contrasts rather than raw. can add raw = TRUE inside of poly() call to make the coefficients be identical. But I think when use emmeans it all works out okay anyway. (e.g., https://stackoverflow.com/questions/69074619/fitting-an-r-linear-model-with-poly-gives-incorrect-coefficients)



#check significance of linear and quad terms in emmeans
test(emtrends(fish_n15_algae_lm_quad1, ~ species, var = "N.15_at_40m", adjust = "fdr", max.degree=2))
test(emtrends(fish_n15_algae_lm_quad2, ~ species, var = "N.15_at_40m", adjust = "fdr", max.degree=2))
#identical results.

#plots - with just 3 levels (matches raw data):----
(mylist2 <- list(
    N.15_at_40m = c(3.043333, 5.233333, 6.003333),
    species = c("Abudefduf septemfasciatus", "Acanthurus triostegus" ,   "Lutjanus fulvus"     ,     
 "Stegastes nigricans")
))
emmip(fish_n15_algae_lm_quad2, species ~ N.15_at_40m,  at = mylist2, CIs = TRUE, plotit=TRUE)

plot_dat2<-emmip(fish_n15_algae_lm_quad2, species ~ N.15_at_40m, at = mylist2, CIs = TRUE, plotit=FALSE)
plot_dat2
fishn15.seabirds.cond.algae %>%
      mutate(species = fct_relevel(species, c("Acanthurus triostegus", "Stegastes nigricans", "Abudefduf septemfasciatus", "Lutjanus fulvus")))%>%
   ggplot(aes(x = N.15_at_40m, y = n15, color = species, fill = species, group = species))+
  geom_point(alpha = .5)+
   geom_ribbon(data = plot_dat2, aes(x = N.15_at_40m, y = yvar, ymin = LCL, ymax=UCL, fill = species), alpha = .2, lwd=0)+
 geom_line(data = plot_dat2, aes(x = N.15_at_40m, y = yvar, color = species, group = species))+
  theme_bw() 

fishn15.seabirds.cond.algae %>%
    group_by(species, N.15_at_40m)%>%
    summarize(mean_n15 = mean(n15))%>%
      mutate(species = fct_relevel(species, c("Acanthurus triostegus", "Stegastes nigricans", "Abudefduf septemfasciatus", "Lutjanus fulvus")))%>%
   ggplot(aes(x = N.15_at_40m, y = mean_n15, color = species, fill = species, group = species))+
  geom_point(alpha = .5)+ # position = position_dodge(0.1)
  # geom_ribbon(data = plot_dat2, aes(x = N.15_at_40m, y = yvar, ymin = LCL, ymax=UCL, fill = species), alpha = .2, lwd=0)+
 geom_line(data = plot_dat2, aes(x = N.15_at_40m, y = yvar, color = species, group = species))+
  geom_errorbar(data = plot_dat2, aes(x = N.15_at_40m, y = yvar, ymin =LCL, ymax=UCL, color = species), alpha = .5, width = .1)+ #, position = position_dodge(0.1)
  theme_bw() 


#plots - continuous within full data range:----
(mylist3 <- list(
    N.15_at_40m = seq(3,6,.1),
    species = c("Abudefduf septemfasciatus", "Acanthurus triostegus" ,   "Lutjanus fulvus"     ,     
 "Stegastes nigricans")
))
plot_dat3<-emmip(fish_n15_algae_lm_quad2, species ~ N.15_at_40m, at = mylist3, CIs = TRUE, plotit=FALSE)
plot_dat3

fishn15.seabirds.cond.algae %>%
      mutate(species = fct_relevel(species, c("Acanthurus triostegus", "Stegastes nigricans", "Abudefduf septemfasciatus", "Lutjanus fulvus")))%>%
   ggplot(aes(x = N.15_at_40m, y = m15, color = species, fill = species, group = species))+
  geom_point(alpha = .5)+
   geom_ribbon(data = plot_dat3, aes(x = N.15_at_40m, y = yvar, ymin = LCL, ymax=UCL, fill = species), alpha = .2, lwd=0)+
 geom_line(data = plot_dat3, aes(x = N.15_at_40m, y = yvar, color = species, group = species))+
  theme_bw() 


#another possible formula...still looks all the same:
fish_n15_algae_lm_poly <- lm(n15 ~ poly(N.15_at_40m, degree = 2)*species, data = fishn15.seabirds.cond.algae)
test(emtrends(fish_n15_algae_lm_poly, ~ species, var = "N.15_at_40m", adjust = "fdr", max.degree=2))


#compare linear to polynomial model, LRT:-----
fish_n15_algae_lm_linear <- lm(n15 ~ N.15_at_40m*species, data = fishn15.seabirds.cond.algae)
test(emtrends(fish_n15_algae_lm_linear, ~ species, var = "N.15_at_40m", adjust = "fdr"))
#only weird thing is here all linear estimates are positive, whereas in polynomial formauls some linear coefficients are negative...

anova(fish_n15_algae_lm_linear, fish_n15_algae_lm_poly, fish_n15_algae_lm_quad1, fish_n15_algae_lm_quad2)
anova(fish_n15_algae_lm_linear, fish_n15_algae_lm_quad2)
anova(fish_n15_algae_lm_linear, fish_n15_algae_lm_quad1)
##quadratic/polynomial model is WAY better fit than linear model. AND all quadratic/polynomial models looks the same, so that's good!


```



#OR here because only 3 values anyway, just treat as factor:--------
```{r}

fish_n15_algae_lm_factor<-lm(n15~ as.factor(N.15_at_40m)*species, 
                          data = fishn15.seabirds.cond.algae)
summary(fish_n15_algae_lm_factor)
anova(fish_n15_algae_lm_factor)#everything significant
Anova(fish_n15_algae_lm_factor)
plot(fish_n15_algae_lm_factor)


#look at emmeans:
fish_n15_algae_lm_factor %>% 
  emmeans(~ N.15_at_40m|species,
          type = "response") 


EMM_fish_n15 <- emmeans(fish_n15_algae_lm_factor, ~ species * N.15_at_40m)

pairs(EMM_fish_n15, simple = "N.15_at_40m", type = "response")

emmeans(fish_n15_algae_lm_factor, list(pairwise ~ N.15_at_40m|species), adjust = "fdr")




```



#correlation test
```{r}
##also include n15 at various distances just to see if matches up:

fishn15.seabirds.cond.algae<-
  left_join(fishn15.seabirds.cond.r, 
            select(algae_n15, c("site.name", "N.15_at_10m", "N.15_at_20m","N.15_at_30m","N.15_at_40m")), 
            by = "site.name")
fishn15.seabirds.cond.algae


##separate fish species----
#a little complicated bc different sample sizes for different species/site combos:
fishn15.seabirds.long<- 
  fishn15.seabirds.cond.algae %>%
    select(c(site.name, species, n15, breeding_biomass_kgha_side, N.15_at_10m, N.15_at_20m, N.15_at_30m, N.15_at_40m))%>%
  group_by(site.name, species) %>%
  mutate(Index=row_number())%>%
  relocate(Index, .before = site.name)
fishn15.seabirds.long

fishn15.seabirds.wide <- 
  pivot_wider(fishn15.seabirds.long,names_from = c("species"),values_from = c("n15"))
fishn15.seabirds.wide

corr_mat_fish_n15_sb_sp<-as.data.frame(fishn15.seabirds.wide[c(3,7:11)]) #only need to start with seabird biomass and offshore algae

cor(corr_mat_fish_n15_sb_sp, method = "spearman", use = "pairwise.complete.obs")
cor(corr_mat_fish_n15_sb_sp, method = "pearson", use = "pairwise.complete.obs")

##spearman:
cor.mat_sb_fishn15_byspp<- cor(fishn15.seabirds.wide[c(3,7,8,10,11,9)], method = "spearman", use = "pairwise.complete.obs")
cor.mat_sb_fishn15_byspp
corrplot(cor.mat_sb_fishn15_byspp, type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5)

##pearson:
cor.mat_sb_fishn15_byspp_pearson<- cor(fishn15.seabirds.wide[c(3,7,8,10,11,9)], method = "pearson", use = "pairwise.complete.obs")
cor.mat_sb_fishn15_byspp_pearson
corrplot(cor.mat_sb_fishn15_byspp_pearson, type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5)


##spearman, no algae:
cor.mat_sb_fishn15_byspp_no_algae<- cor(fishn15.seabirds.wide[c(3,8,10,11,9)], method = "spearman", use = "pairwise.complete.obs")
cor.mat_sb_fishn15_byspp_no_algae
corrplot(cor.mat_sb_fishn15_byspp_no_algae, type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5)

##save outputs----
#chunk 1
pdf(file = "../output/seabird-fishn15/seabirds_fishn15_corr_plot_by_sp_SPEARMAN.pdf")
corrplot(cor.mat_sb_fishn15_byspp, type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5)
dev.off()


#chunk 2
pdf(file = "../output/seabird-fishn15/seabirds_fishn15_corr_plot_by_sp_PEARSON.pdf")
corrplot(cor.mat_sb_fishn15_byspp_pearson, type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5)
dev.off()


##Oh wait, all a bit weird because of NAs, and correlations among fish species depend on order-----
cor(fishn15.seabirds.wide[c(3,8,10,11,9)], method = "spearman", use = "pairwise.complete.obs")
cor(fishn15.seabirds.wide[c(3,10)], method = "spearman", use = "pairwise.complete.obs")
cor(fishn15.seabirds.wide[c(3,11)], method = "spearman", use = "pairwise.complete.obs")
cor(fishn15.seabirds.wide[c(3,9)], method = "spearman", use = "pairwise.complete.obs")
cor(fishn15.seabirds.wide[c(3,8)], method = "spearman", use = "pairwise.complete.obs")
#okay, each species corr with seabird biomass matches*

#what if we arrange within each species/biomass level, n15 from high to low:
fishn15.seabirds.long2<- 
  fishn15.seabirds.cond.algae %>%
    select(c(site.name, species, n15, breeding_biomass_kgha_side, N.15_at_10m, N.15_at_20m, N.15_at_30m, N.15_at_40m))%>%
    arrange(desc(n15))%>%
  group_by(site.name, species) %>%
  mutate(Index=row_number())%>%
  relocate(Index, .before = site.name)
fishn15.seabirds.long

fishn15.seabirds.wide2 <- 
  pivot_wider(fishn15.seabirds.long2,names_from = c("species"),values_from = c("n15"))
fishn15.seabirds.wide2

corrplot(cor(fishn15.seabirds.wide2[c(3,8,11,9, 10)], method = "spearman", use = "pairwise.complete.obs"), type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5)

cor(fishn15.seabirds.wide2[c(3,8,11,9, 10)], method = "spearman", use = "pairwise.complete.obs")
cor(fishn15.seabirds.wide[c(3,8,10,11,9)], method = "spearman", use = "pairwise.complete.obs")
#YUP, now really different cors***
#SO: can't show correlations across different fish species, unless we were to take a mean per site or something, but then we'd only have 3 points....


###save:----
cor.mat_sb_fishn15_byspp_no_algae<- cor(fishn15.seabirds.wide[c(3,8,10,11,9)], method = "spearman", use = "pairwise.complete.obs")

cor.mat_sb_fishn15_fish_by_sb_only<- cor(x = fishn15.seabirds.wide[c(3)], y =fishn15.seabirds.wide[c(8,10,11,9)], method = "spearman", use = "pairwise.complete.obs")



pdf(file = "../output/seabird-fishn15/seabirds_fishn15_corr_plot_by_sp_sb_onlySPEARMAN.pdf")
corrplot(cor.mat_sb_fishn15_fish_by_sb_only, type = "full",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5)
dev.off()


pdf(file = "../output/seabird-fishn15/seabirds_fishn15_corr_plot_by_sp_sb_onlySPEARMAN_LEGEND.pdf")
corrplot(cor.mat_sb_fishn15_byspp_no_algae, type = "full",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5, cl.pos = "b")
dev.off()


#try with seabirds and algae:
cor.mat_sb_fishn15_fish_by_sb_algae_only<- cor(x = fishn15.seabirds.wide[c(3,4,5,6,7)], y =fishn15.seabirds.wide[c(8,10,11,9)], method = "spearman", use = "pairwise.complete.obs")


```



#any way to combine algae and fish corr plots?? - NOPE


##simple boxplot of fish n15 veruss managemetn status
```{r}
fishn15_box<-
  fishn15.seabirds.cond.algae%>%
        mutate(species = fct_relevel(species, c("Acanthurus triostegus", "Stegastes nigricans", "Abudefduf septemfasciatus", "Lutjanus fulvus")))%>%
  ggplot(aes(x = species, y = n15, fill = motu))+
  geom_boxplot(alpha = .5, outlier.shape = NA)+ #
  geom_point(aes(color= motu), position = position_dodge(.75), size = 2.5, alpha = .7)+
  ylab(expression(Fish~delta^15~N))+
  xlab("")+
  scale_fill_manual(values = c('#2F9D3E', '#F2BB05', '#CD1913'), labels = c('reference','recovering','unrestored'), name = "")+
  scale_colour_manual(values = c('#2F9D3E', '#F2BB05', '#CD1913'), labels = c('reference','recovering','unrestored'), name = "")+
      scale_x_discrete(labels = c("A. triostegus\n(herbivore)", "S. nigricans\n(herbivore)", "A. septemfasciatus\n(omnivore)", "L. fulvus\n(piscivore)"))+
   theme_bw()+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
        axis.text = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = c(.9, .85),
        legend.text = element_text(size = 12))
fishn15_box


ggsave("../output/seabird-fishn15/fishn15_box.jpg", plot = fishn15_box, width = 7, height = 5)

```






