---
title: "seabirds_vs_fish_n15"
author: "CEB"
date: '2023-09-29'
output: html_document
---

#load packages
```{r}
library(tidyverse)

library(lme4)
library(car)
library(jtools)

library(emmeans)

library(corrplot)

```


#load data
```{r}
seabirds <- read.csv("../output/n15_seabirds_combined_no_iti.csv", strip.white = T, header = T)
fish_n15 <- read.csv("../../fish_isotopes/raw_data/fish_isotopes_focal_spp_only.csv", stringsAsFactors = TRUE)

```

#merge data
```{r}
#make combined site name column in fish_n15

fish_n15_dat<-
  fish_n15%>%
  mutate(protection = if_else(wind.exposure == "leeward", "Protected", "Exposed"))%>%
  unite("site.name", c(motu, protection), sep = "_", remove = FALSE)

fish_n15_dat

fishn15.seabirds<-left_join(select(fish_n15_dat, c("site.name", "fish.id", "species", 
                                                   "month.caught", "year.caught", "protection", "n15",
                                                   "c13", "n.percent", "c.percent")),
                            select(seabirds, c("site.name", "breeding_biomass_kgha_side")), 
                                   by = "site.name")%>%
  mutate(site.name = as.factor(site.name))
fishn15.seabirds



```


#quick plot
```{r}
fishn15.seabirds%>%
  ggplot(aes(x = breeding_biomass_kgha_side, y = n15, color = species, fill = species))+
  facet_wrap(~species, scales = "free")+
  geom_point()+
  geom_smooth(method = "lm")


fishn15.seabirds%>%
  ggplot(aes(x = log(breeding_biomass_kgha_side), y = n15, color = species, fill = species))+
  facet_wrap(~species, scales = "free")+
  geom_point()+
  geom_smooth(method = "lm")

fishn15.seabirds%>%
  ggplot(aes(x = log(breeding_biomass_kgha_side), y = log(n15), color = species, fill = species))+
  facet_wrap(~species, scales = "free")+
  geom_point()+
  geom_smooth(method = "lm")


#check sample sizes:
fishn15.seabirds%>%
  group_by(species, site.name)%>%
  summarize(n = length(n15))


##plot based on motu/site----
fishn15.seabirds%>%
  ggplot(aes(x = site.name, y = n15, color = species, fill = species))+
  facet_wrap(~species, scales = "free")+
  geom_boxplot(alpha = .5)

#arrange based on seabird density
fishn15.seabirds%>%
  mutate(site.name = fct_relevel(site.name, "Rimatuu_Protected", "Reiono_Exposed", "Aie_Exposed", "Aie_Protected"))%>%
  ggplot(aes(x = site.name, y = n15, color = species, fill = species))+
  facet_wrap(~species, scales = "free")+
  geom_boxplot(alpha = .5)+
  geom_point(alpha = .7)
  

##plot with means and se's----

fishn15.seabirds%>%
  group_by(species, breeding_biomass_kgha_side)%>%
  summarize(mean_n15 = mean(n15),
            n_n15 = length(n15),
            se_n15 = sd(n15)/sqrt(n_n15))%>%
  ggplot(aes(x = breeding_biomass_kgha_side, y = mean_n15, color = species, fill = species))+
  geom_point( alpha = .5)+
  geom_errorbar(aes(ymin = (mean_n15-se_n15), ymax = (mean_n15+se_n15)), alpha = .5)+
  geom_line(alpha = .5)+
  theme_bw()


fishn15.seabirds%>%
  group_by(species, breeding_biomass_kgha_side)%>%
  summarize(mean_n15 = mean(n15),
            n_n15 = length(n15),
            se_n15 = sd(n15)/sqrt(n_n15))%>%
  ggplot(aes(x = breeding_biomass_kgha_side, y = mean_n15, color = species, fill = species))+
  geom_point( alpha = .5)+
  geom_errorbar(aes(ymin = (mean_n15-se_n15), ymax = (mean_n15+se_n15)), alpha = .5)+
  geom_line(alpha = .5)+
  theme_bw()+
  facet_wrap(~species)


#****relationships definitely don't look linear, and only 4 points. So I think it does make sense to use factor levels for this one just to show approximate patterns-------



###make biplots-----
fishn15.seabirds %>%
    mutate(site.name = fct_relevel(site.name, "Rimatuu_Protected", "Reiono_Exposed", "Aie_Exposed", "Aie_Protected"))%>%
  ggplot(aes(x = c13, y = n15, colour = site.name, fill = site.name, shape = site.name)) + 
    geom_point(size = 3, alpha= .6)+
  stat_ellipse(geom = "polygon", alpha = .05, level = .75)+
  facet_wrap(~species, scales = 'free')+
    theme_bw()+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank()
        )
  
```

#correlation test
```{r}

##also include n15 at various distances just to see if matches up:
fishn15.seabirds_for.corr<-left_join(select(fish_n15_dat, c("site.name", "fish.id", "species", 
                                                   "month.caught", "year.caught", "n15",
                                                   "c13", "n.percent", "c.percent")),
                            select(seabirds, c("site.name", "breeding_biomass_kgha_side", "N.15_at_10m", "N.15_at_20m", "N.15_at_30m", "N.15_at_40m")), 
                                   by = "site.name")%>%
  mutate(site.name = as.factor(site.name))
fishn15.seabirds_for.corr

##aggregated by fish species---
corr_mat_fish_n15_sb<-as.data.frame(fishn15.seabirds_for.corr[,6:14])

cor.mtest(corr_mat_fish_n15_sb)

cor.mat_sb_fishn15<- cor(corr_mat_fish_n15_sb, use = "pairwise.complete.obs")
cor.mat_sb_fishn15

corrplot(cor(corr_mat_fish_n15_sb, use = "pairwise.complete.obs"), type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5, title = "Seabirds - Fish N15")



##separate fish species----
#a little complicated bc different sample sizes for different species/site combos:
fishn15.seabirds.long<- 
  fishn15.seabirds_for.corr %>%
    select(c(site.name, species, n15, breeding_biomass_kgha_side, N.15_at_10m, N.15_at_20m, N.15_at_30m, N.15_at_40m))%>%
  group_by(site.name, species) %>%
  mutate(Index=row_number())%>%
  relocate(Index, .before = site.name)
fishn15.seabirds.long

fishn15.seabirds.wide <- 
  pivot_wider(fishn15.seabirds.long,names_from = c("species"),values_from = "n15")
fishn15.seabirds.wide

corr_mat_fish_n15_sb_sp<-as.data.frame(fishn15.seabirds.wide[,3:12])

cor.mtest(corr_mat_fish_n15_sb_sp)

cor.mat_sb_fishn15_byspp<- cor(corr_mat_fish_n15_sb_sp, use = "pairwise.complete.obs")
cor.mat_sb_fishn15_byspp


corrplot(cor(corr_mat_fish_n15_sb_sp, use = "pairwise.complete.obs"), type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5, title = "Seabirds - Fish Species N15")



##save outputs----
write.csv(cor.mat_sb_fishn15, "../output/seabird-fishn15/seabirds_fish_n15_corrmatrix.csv")
write.csv(cor.mat_sb_fishn15_byspp, "../output/seabird-fishn15/seabirds_fish_n15_by_species_corrmatrix.csv")


#chunk 2
pdf(file = "../output/seabird-fishn15/seabirds_fishn15_corr_plot.pdf")

corrplot(cor(corr_mat_fish_n15_sb, use = "pairwise.complete.obs"), type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5, title = "Seabirds Fish N15")

dev.off()

#chunk 3
pdf(file = "../output/seabird-fishn15/seabirds_fishn15_by_species_corr_plot.pdf")

corrplot(cor(corr_mat_fish_n15_sb_sp, use = "pairwise.complete.obs"), type = "upper",
         addCoef.col = NULL, addCoefasPercent = FALSE, tl.col = "black", tl.cex = 0.5, title = "Seabirds Fish N15")

dev.off()


```



#quick analysis
```{r}
#interaction, non-log----
seabird_fish_n15_mod1<-lmer(n15~ breeding_biomass_kgha_side*species + (1|site.name), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_mod1)
vif(seabird_fish_n15_mod1)
plot(seabird_fish_n15_mod1)

plot_summs(seabird_fish_n15_mod1)
summ(seabird_fish_n15_mod1)
anova(seabird_fish_n15_mod1)
Anova(seabird_fish_n15_mod1)


#differences by species and species*breeding biomass...

#use emmeans to figure out what's happening:
seabird_fish_n15_mod1 %>% 
  emmeans(~ species, var = "breeding_biomass_kgha_side") 

seabird_fish_n15_mod1 %>% 
emtrends(pairwise ~ species, var = "breeding_biomass_kgha_side")

# plot
range(fishn15.seabirds$breeding_biomass_kgha_side)
levels(fishn15.seabirds$species)
(mylist <- list(
    breeding_biomass_kgha_side = seq(5, 380, by = 50),
    species = c("Abudefduf septemfasciatus", "Acanthurus triostegus" ,    "Cephalopholis argus"   ,    "Lutjanus fulvus"     ,     
 "Stegastes nigricans")
))

emmip(seabird_fish_n15_mod1, species ~ breeding_biomass_kgha_side, at = mylist, CIs = TRUE)


#more emmeans
seabird_fish_n15_mod1 %>% 
  emmeans(~breeding_biomass_kgha_side, by = "species") 

emtrends(seabird_fish_n15_mod1,  ~ species, var = "breeding_biomass_kgha_side")

emmip(seabird_fish_n15_mod1, species ~ breeding_biomass_kgha_side, cov.reduce = range)


#interaction, log----
seabird_fish_n15_log_mod1<-lmer(n15~ log(breeding_biomass_kgha_side)*species + (1|site.name), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_log_mod1)
vif(seabird_fish_n15_log_mod1)
plot(seabird_fish_n15_log_mod1)

plot_summs(seabird_fish_n15_log_mod1)
summ(seabird_fish_n15_log_mod1)
anova(seabird_fish_n15_log_mod1)
Anova(seabird_fish_n15_log_mod1)

emmip(seabird_fish_n15_log_mod1, species ~ breeding_biomass_kgha_side, cov.reduce = range, CIs = TRUE)


emtrends(seabird_fish_n15_log_mod1,  ~ species, var = "breeding_biomass_kgha_side", level = .95)
emtrends(seabird_fish_n15_mod1,  ~ species, var = "breeding_biomass_kgha_side", level = .95)

emtrends(seabird_fish_n15_log_mod1,  ~ species, var = "breeding_biomass_kgha_side", level = .9)
emtrends(seabird_fish_n15_mod1,  ~ species, var = "breeding_biomass_kgha_side", level = .9)


emtrends(seabird_fish_n15_log_mod1,  ~ species, var = "breeding_biomass_kgha_side", level = .75)
emtrends(seabird_fish_n15_mod1,  ~ species, var = "breeding_biomass_kgha_side", level = .75)

#looks like only  Abudefduf septemfasciatus is significant regardless of level used...at .95 only sig when use log...


##interaction - log x2----
fishn15.seabirds<-
  fishn15.seabirds%>%
  mutate(log_breeding_biomass_kgha_side = log(breeding_biomass_kgha_side))

seabird_fish_n15_log_mod2<-lmer(n15~ log_breeding_biomass_kgha_side*species + (1|site.name), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_log_mod2)
plot(seabird_fish_n15_log_mod2)

plot_summs(seabird_fish_n15_log_mod2)
summ(seabird_fish_n15_log_mod2)
anova(seabird_fish_n15_log_mod2)
Anova(seabird_fish_n15_log_mod2)

emmip(seabird_fish_n15_log_mod2, species ~ log_breeding_biomass_kgha_side, cov.reduce = range, CIs = TRUE)


emtrends(seabird_fish_n15_log_mod2,  ~ species, var = "log_breeding_biomass_kgha_side", level = .95)
emtrends(seabird_fish_n15_log_mod2,  ~ species, var = "log_breeding_biomass_kgha_side", level = .75)


##interaction - log x2, 0 + formula----
seabird_fish_n15_log_mod3<-lmer(n15~ 0 + log_breeding_biomass_kgha_side*species + (1|site.name), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_log_mod3)
plot(seabird_fish_n15_log_mod3)

plot_summs(seabird_fish_n15_log_mod3)
summ(seabird_fish_n15_log_mod3)
anova(seabird_fish_n15_log_mod3)
Anova(seabird_fish_n15_log_mod3)

emmip(seabird_fish_n15_log_mod3, species ~ log_breeding_biomass_kgha_side, cov.reduce = range, CIs = TRUE)


emtrends(seabird_fish_n15_log_mod3,  ~ species, var = "log_breeding_biomass_kgha_side", level = .95)

#doesn't really help**


#try with species as random effect----
seabird_fish_n15_mod2<-lmer(n15~ breeding_biomass_kgha_side + (1|site.name) + (1|species), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_mod2)
plot(seabird_fish_n15_mod2)

plot_summs(seabird_fish_n15_mod2)
summ(seabird_fish_n15_mod2)
anova(seabird_fish_n15_mod2)
Anova(seabird_fish_n15_mod2)
#nothing happening

seabird_fish_n15_mod3<-lmer(n15~ breeding_biomass_kgha_side + (species|site.name), 
                          data = fishn15.seabirds)
#SINGULAR


#additive model ----
seabird_fish_n15_log_mod4<-lmer(n15~log_breeding_biomass_kgha_side+species + (1|site.name), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_log_mod4)
plot_summs(seabird_fish_n15_log_mod4)


##interaction, log-log----
fishn15.seabirds<-
  fishn15.seabirds%>%
  mutate(log_n15 = log(n15))

seabird_fish_n15_log_log_mod1<-lmer(log_n15~ log_breeding_biomass_kgha_side*species + (1|site.name), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_log_log_mod1)
plot(seabird_fish_n15_log_log_mod1)

plot_summs(seabird_fish_n15_log_log_mod1)
summ(seabird_fish_n15_log_log_mod1)
anova(seabird_fish_n15_log_log_mod1)
Anova(seabird_fish_n15_log_log_mod1)

emmip(seabird_fish_n15_log_log_mod1, species ~ log_breeding_biomass_kgha_side, cov.reduce = range, CIs = TRUE)

emmip(seabird_fish_n15_log_log_mod1, species ~ log_breeding_biomass_kgha_side, at = list(log_breeding_biomass_kgha_side = c(5.4, 115.4, 128, 378.7)), CIs = TRUE)


emtrends(seabird_fish_n15_log_log_mod1,  ~ species, var = "log_breeding_biomass_kgha_side", level = .95)
emtrends(seabird_fish_n15_log_log_mod1,  ~ species, var = "log_breeding_biomass_kgha_side", level = .75)


seabird_fish_n15_log_log_mod1.rg <- update(ref_grid(seabird_fish_n15_log_log_mod1), tran = "log") # can use log response and still backtransform with emmeans

seabird_fish_n15_log_log_mod1.rg %>% 
  emmeans(~log_breeding_biomass_kgha_side |species,
          type = "response") 


emmip(seabird_fish_n15_log_log_mod1.rg, species ~ log_breeding_biomass_kgha_side, cov.reduce = range, CIs = TRUE)


##try model including year and month-------
seabird_fish_n15_mod1B<-lmer(n15~ breeding_biomass_kgha_side*species + month.caught + year.caught + (1|site.name), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_mod1B)
plot_summs(seabird_fish_n15_mod1B)
Anova(seabird_fish_n15_mod1B)
#not high enough sample size to include both....


seabird_fish_n15_mod1B<-lmer(n15~ breeding_biomass_kgha_side*species  + year.caught + (1|site.name), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_mod1B)
plot_summs(seabird_fish_n15_mod1B)
Anova(seabird_fish_n15_mod1B)

#BUT DOESNT LOOK LIKE IT MATTERS****



```


#by individual species:
```{r}

#ab sept----
seabird_asep_n15_mod1<-lmer(n15~ breeding_biomass_kgha_side + (1|site.name), 
                          data = fishn15.seabirds[fishn15.seabirds$species == "Abudefduf septemfasciatus",])
summary(seabird_asep_n15_mod1)
plot(seabird_asep_n15_mod1)

plot_summs(seabird_asep_n15_mod1)
summ(seabird_asep_n15_mod1)

#log
seabird_asep_n15_log_mod1<-lmer(n15~ log(breeding_biomass_kgha_side) + (1|site.name), 
                          data = fishn15.seabirds[fishn15.seabirds$species == "Abudefduf septemfasciatus",])
summary(seabird_asep_n15_log_mod1)
plot(seabird_asep_n15_log_mod1)

plot_summs(seabird_asep_n15_log_mod1)
summ(seabird_asep_n15_log_mod1)


##a tri---
seabird_atri_n15_mod1<-lmer(n15~ breeding_biomass_kgha_side + (1|site.name), 
                          data = fishn15.seabirds[fishn15.seabirds$species == "Acanthurus triostegus",])

summary(seabird_atri_n15_mod1)
plot(seabird_atri_n15_mod1)

plot_summs(seabird_atri_n15_mod1)
summ(seabird_atri_n15_mod1)


#grouper----
seabird_carg_n15_mod1<-lmer(n15~ breeding_biomass_kgha_side + (1|site.name), 
                          data = fishn15.seabirds[fishn15.seabirds$species == "Cephalopholis argus",])

summary(seabird_carg_n15_mod1)
plot(seabird_carg_n15_mod1)

plot_summs(seabird_carg_n15_mod1)
summ(seabird_carg_n15_mod1)


#log
seabird_carg_n15_log_mod1<-lmer(n15~ log(breeding_biomass_kgha_side) + (1|site.name), 
                          data = fishn15.seabirds[fishn15.seabirds$species == "Cephalopholis argus",])

summary(seabird_carg_n15_log_mod1)
plot(seabird_carg_n15_log_mod1)

plot_summs(seabird_carg_n15_log_mod1)
summ(seabird_carg_n15_log_mod1)
Anova(seabird_carg_n15_log_mod1)
#trending**

##snapper----
seabird_lful_n15_mod1<-lmer(n15~ breeding_biomass_kgha_side + (1|site.name), 
                          data = fishn15.seabirds[fishn15.seabirds$species == "Lutjanus fulvus",])

summary(seabird_lful_n15_mod1)
plot(seabird_lful_n15_mod1)

plot_summs(seabird_lful_n15_mod1)
summ(seabird_lful_n15_mod1)

#log
seabird_lful_n15_log_mod1<-lmer(n15~ log(breeding_biomass_kgha_side) + (1|site.name), 
                          data = fishn15.seabirds[fishn15.seabirds$species == "Lutjanus fulvus",])

summary(seabird_lful_n15_log_mod1)
plot(seabird_lful_n15_log_mod1)

plot_summs(seabird_lful_n15_log_mod1)
summ(seabird_lful_n15_log_mod1)


#stegastes----
seabird_snig_n15_mod1<-lmer(n15~ breeding_biomass_kgha_side + (1|site.name), 
                          data = fishn15.seabirds[fishn15.seabirds$species == "Stegastes nigricans",])

summary(seabird_snig_n15_mod1)
plot(seabird_snig_n15_mod1)

plot_summs(seabird_snig_n15_mod1)
summ(seabird_snig_n15_mod1)

#log
seabird_snig_n15_log_mod1<-lmer(n15~ log(breeding_biomass_kgha_side) + (1|site.name), 
                          data = fishn15.seabirds[fishn15.seabirds$species == "Stegastes nigricans",])

summary(seabird_snig_n15_log_mod1)
plot(seabird_snig_n15_log_mod1)

plot_summs(seabird_snig_n15_log_mod1)
summ(seabird_snig_n15_log_mod1)
anova(seabird_snig_n15_log_mod1)
Anova(seabird_snig_n15_log_mod1)



###some trends....

```


##BECAUSE OF LOW SAMPLE SIZES AND ONLY 4 LEVELS, COMBINE INTO LOW, MED, HIGH SEABIRDS
```{r}
seabirds
#these 4 sites:
#Aie protected = 378.720000	
#Aie exposed = 128.000000	
#Reiono exposed = 115.353333
#Rimatuu protected = 5.390526


fishn15.seabirds<-
  fishn15.seabirds%>%
  mutate(seabird_level = case_when(breeding_biomass_kgha_side<7 ~"low",
                                   breeding_biomass_kgha_side>7&breeding_biomass_kgha_side <200 ~"mid",
                                   breeding_biomass_kgha_side>200 ~"high"))%>%
  mutate(seabird_level = as.factor(seabird_level))%>%
  mutate(seabird_level = fct_relevel(seabird_level, "low", "mid", "high"))


##re-plot----
fishn15.seabirds%>%
  ggplot(aes(x = seabird_level, y = n15, color = species, fill = species))+
  facet_wrap(~species, scales = "free")+
  geom_boxplot(alpha = .5)+
  geom_point(alpha = .7)


##run analysis----
seabird_fish_n15_levels_mod1<-lmer(n15~ seabird_level*species + (1|site.name), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_levels_mod1)
plot(seabird_fish_n15_levels_mod1)

plot_summs(seabird_fish_n15_levels_mod1)
summ(seabird_fish_n15_levels_mod1)
anova(seabird_fish_n15_levels_mod1)
Anova(seabird_fish_n15_levels_mod1)


#use emmeans----
seabird_fish_n15_levels_mod1 %>% 
  emmeans(~ seabird_level|species) 

emmip(seabird_fish_n15_levels_mod1, species ~ seabird_level)


#pairwise:
seabird_fish_n15_levels_mod1 %>% 
  emmeans(~ seabird_level|species) %>%
  pairs

emmeans(seabird_fish_n15_levels_mod1, pairwise ~ seabird_level | species)


seabird_fish_n15_levels_mod1 %>% 
  emmeans(~ seabird_level|species) %>%
  eff_size(sigma = sigma(seabird_fish_n15_levels_mod1), edf = Inf)


EMM <- emmeans(seabird_fish_n15_levels_mod1, ~ species * seabird_level)
pairs(EMM, simple = "seabird_level")
test(pairs(EMM, by = "species"), by = NULL, adjust = "mvt")
test(pairs(EMM, by = "species"), by = NULL, adjust = "none")
#nothing actually "significant" but trends definitely there*

test(pairs(EMM, by = "species"), by = NULL, adjust = "none", level = 0.9, interval = c("confidence"))
predict(EMM, interval = c("confidence"), level = 0.9)


confint(pairs(EMM, by = "species"), by = NULL, adjust = "none", level = 0.75, interval = c("confidence"))


##species as random effect----
seabird_fish_n15_levels_mod2<-lmer(n15~ seabird_level + (1|site.name) + (1|species), 
                          data = fishn15.seabirds)
summary(seabird_fish_n15_levels_mod2)
anova(seabird_fish_n15_levels_mod2)
Anova(seabird_fish_n15_levels_mod2)


plot_summs(seabird_fish_n15_levels_mod2, ci_level = .95, inner_ci_level = .75)
summ(seabird_fish_n15_levels_mod2)

#I don't think this is right. Lots of variance explained in random effects, but not fixed effects. and not easy way to see species diffs. 


##try with additional variables-----
seabird_fish_n15_levels_mod3<-lmer(n15~ seabird_level*species  + year.caught + month.caught + (1|site.name), 
                          data = fishn15.seabirds)
#WARNING - fixed-effect model matrix is rank deficient so dropping 1 column / coefficient
summary(seabird_fish_n15_levels_mod3)
plot(seabird_fish_n15_levels_mod3)
Anova(seabird_fish_n15_levels_mod3) #all sig except year and month


#try including exposure:
seabird_fish_n15_levels_mod4<-lmer(n15~ seabird_level*species  + protection + (1|site.name), 
                          data = fishn15.seabirds)
#WARNING - fixed-effect model matrix is rank deficient so dropping 1 column / coefficient
summary(seabird_fish_n15_levels_mod4)
plot(seabird_fish_n15_levels_mod4)
Anova(seabird_fish_n15_levels_mod4) #here have 0 df for protection, so can't use....


#okay, so these don't work....



##can i just plot/report some results from the model with 3 levels:----
plot(seabird_fish_n15_levels_mod1)

emm.summary.sb.fishn15<-
seabird_fish_n15_levels_mod1 %>% 
  emmeans(~ seabird_level|species) 

emm_plot<-emmip(seabird_fish_n15_levels_mod1, species ~ seabird_level, CIs = TRUE, level = c(0.75),
                 CIarg = list(lwd = .9, alpha = .25), lwd = 2, linearg = list(lwd = 1.2, alpha = .8), dotarg = list(lwd = 1.2, alpha = .8))

emm_plot_sb_n15<-
emm_plot+
  ylab("N15")+
  xlab("seabid biomass")+
  labs(colour = "fish species")+
  theme_bw()+
   theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
       # text = element_text(size = 14, family = "Arial"),
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA)
        )
  
emm_plot_sb_n15


ggsave(emm_plot_sb_n15, file = "../output/seabird-fishn15/seabirds_fishn15_interaction_plot.pdf",
       width = 7, height = 5)



##quick biplot with these three groups-----
fish_n15_biplots<-
  fishn15.seabirds %>%
  ggplot(aes(x = c13, y = n15, colour = seabird_level, fill = seabird_level)) + 
    geom_point(size = 3, alpha= .6, aes(shape = site.name))+
  stat_ellipse(geom = "polygon", alpha = .05, level = .75)+
  facet_wrap(~species, scales = 'free')+
    theme_bw()+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank()
        )

ggsave(fish_n15_biplots, file = "../output/seabird-fishn15/fishn15_biplot.pdf",
       width = 9, height = 6)



```


##BECAUSE OF ONLY 4 LEVELS AND MAY NOT BE LINEAR - USE SITES AS FACTORS?
```{r}
seabirds
#these 4 sites:
#Aie protected = 378.720000	
#Aie exposed = 128.000000	
#Reiono exposed = 115.353333
#Rimatuu protected = 5.390526


fishn15.seabirds<-
  fishn15.seabirds%>%
  mutate(site.name = fct_relevel(site.name, "Rimatuu_Protected", "Reiono_Exposed", "Aie_Exposed", "Aie_Protected"))

##re-plot----
fishn15.seabirds%>%
  ggplot(aes(x = site.name, y = n15, color = species, fill = species))+
  facet_wrap(~species, scales = "free")+
  geom_boxplot(alpha = .5)+
  geom_point(alpha = .7)


##run analysis----
seabird_fish_n15_bio_levels_mod1<-lmer(n15~ site.name*species + (1|site.name), 
                          data = fishn15.seabirds)
#a few warnings...
summary(seabird_fish_n15_bio_levels_mod1)
plot(seabird_fish_n15_bio_levels_mod1)

plot_summs(seabird_fish_n15_bio_levels_mod1)
summ(seabird_fish_n15_bio_levels_mod1)
anova(seabird_fish_n15_bio_levels_mod1)
Anova(seabird_fish_n15_bio_levels_mod1)


#use emmeans----
seabird_fish_n15_bio_levels_mod1 %>% 
  emmeans(~ site.name|species) 

emmip(seabird_fish_n15_bio_levels_mod1, species ~ site.name)


#pairwise:
seabird_fish_n15_bio_levels_mod1 %>% 
  emmeans(~ site.name|species) %>%
  pairs

##ALL A BIT WEIRD, DON'T USE. probably weird becasue site in both fixed and random, and small sample sizes-----

```
